site_name: CatPig's study archive

nav:
  - 主页:
    - Welcome: index.md
    - Getting Started: start.md
    - About: about.md
  - Math: natural_science.md
  - 电子: computer_science.md
  - 网安: optional_course.md
  - NULL: course_A.md
  - NULL: course_B.md
  - NULL: course_C.md
  - NULL: course_D.md
  - NULL: course_E.md
  - NULL: acee.md

theme:
  name: material
  logo: 'images/logo.svg'
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.path
    - content.action.edit
  icon:
    repo: fontawesome/brands/git-alt 
    edit: material/pencil 
    view: material/eye
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

repo_url: https://github.com/0X0F7A/studyPage/
repo_name: 0X0F7A/studyPage/
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
